included:
  - Forge
  - ForgeKit
  - ForgeFilterExtension
  - forge-cli
  - ForgeWidget
  - ForgeTests
  - ForgeIntegrationTests
  - ForgeUITests

excluded:
  - DerivedData
  - build
  - .build
  - Pods

disabled_rules:
  - trailing_comma
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fatal_error_message
  - first_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - sorted_first_last
  - yoda_condition

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y
    - i
    - n
